@startuml
mainframe **sd** CariTest
hide footbox

actor "**: User**" as User
boundary "**: TestPage**" as TestListPage
control "**: TestController**" as TestController
entity "**: Test**" as TestCaseRepository

User -> TestListPage : searchTest(keyword)
activate TestListPage

TestListPage -> TestController : processTestSearch(keyword)
activate TestController

TestController -> TestCaseRepository : getByTestKey(keyword)
activate TestCaseRepository
TestCaseRepository --> TestController : testList
deactivate TestCaseRepository

TestController --> TestListPage : testList
deactivate TestController

alt No search results found
    TestListPage -> TestListPage : displayError("No tests found")
    activate TestListPage
    deactivate TestListPage
else Search results found
    TestListPage -> TestListPage : displaySearchResults(testList)
    activate TestListPage
    deactivate TestListPage 
end

deactivate TestListPage
@enduml
