@startuml
mainframe **sd** CariTag
hide footbox

actor "**: User**" as User
boundary "**: TagPage**" as TagPage
control "**: TagController**" as TagController
entity "**: Tag**" as TagRepository

User -> TagPage : searchTag(keyword)
activate TagPage

TagPage -> TagController : processTagSearch(keyword)
activate TagController

TagController -> TagRepository : getByTagName(keyword)
activate TagRepository
TagRepository --> TagController : tagList
deactivate TagRepository

TagController --> TagPage : tagList
deactivate TagController

alt No search results found
    TagPage -> TagPage : displayError("No tags found")
    activate TagPage
    deactivate TagPage
else Search results found
    TagPage -> TagPage : displaySearchResults(tagList)
    activate TagPage
    deactivate TagPage
end

deactivate TagPage
@enduml
