@startuml
mainframe **sd** CariReport
hide footbox

actor "**: User**" as User
boundary "**: ReportPage**" as ReportListPage
control "**: ReportController**" as ReportController
entity "**: Report**" as ReportRepository

User -> ReportListPage : search(keyword)
activate ReportListPage

ReportListPage -> ReportController : findReports(keyword)
activate ReportController

ReportController -> ReportRepository : getByReportKey(keyword)
activate ReportRepository
ReportRepository --> ReportController : reportList
deactivate ReportRepository

ReportController --> ReportListPage : reportList
deactivate ReportController

alt No search results found
    ReportListPage -> ReportListPage : displayError("No reports found")
    activate ReportListPage
    deactivate ReportListPage
else Search results found
    ReportListPage -> ReportListPage : displaySearchResults(reportList)
    activate ReportListPage
    deactivate ReportListPage
end

deactivate ReportListPage
@enduml
