@startuml
mainframe **sd** DaftarTag
hide footbox

actor "**: User**" as User
boundary "**: TagPage**" as TagManagementPage
control "**: TagController**" as TagController
entity "**: Tag**" as TagRepository

User -> TagManagementPage : viewTags()
activate TagManagementPage

TagManagementPage -> TagController : loadTags()
activate TagController

TagController -> TagRepository : getAllTags()
activate TagRepository

TagRepository --> TagController : tagList
deactivate TagRepository

TagController --> TagManagementPage : tagList
deactivate TagController

alt tagList is empty
    TagManagementPage -> TagManagementPage : displayMessage("No tags found")
    activate TagManagementPage
    deactivate TagManagementPage
else tagList is not empty
    TagManagementPage -> TagManagementPage : displayTags(tagList)
    activate TagManagementPage
    deactivate TagManagementPage
end

deactivate TagManagementPage

@enduml