@startuml
mainframe **sd** HapusTest
hide footbox

actor "**: User**" as User
boundary "**: DetailReportPage**" as DetailReportPage
control "**: TestController**" as TestController
entity "**: Test**" as TestCaseRepository

User -> DetailReportPage : clickDeleteTest(testCaseID)
activate DetailReportPage

DetailReportPage -> DetailReportPage : displayConfirmationDialog()
activate DetailReportPage
deactivate DetailReportPage
alt User cancels
    User -> DetailReportPage : cancelDelete()

else User confirms
    User -> DetailReportPage : confirmDelete(testCaseID)
    DetailReportPage -> TestController : deleteTest(testCaseID)
    activate TestController

    TestController -> TestCaseRepository : deleteTestByID(testCaseID)
    activate TestCaseRepository

    TestCaseRepository --> TestController : deleteStatus
    deactivate TestCaseRepository

    TestController --> DetailReportPage : deleteStatus
    deactivate TestController

    DetailReportPage -> DetailReportPage : reloadTestList()
    activate DetailReportPage

    deactivate DetailReportPage
end
@enduml