@startuml
mainframe "**sd** UbahTag"

hide footbox

actor "**: User**" as User
boundary "**: TagPage**" as TagDetailPage
control "**: TagController**" as TagController
entity  "**: Tag**" as TagRepository

User -> TagDetailPage : clickEdit()
activate TagDetailPage

TagDetailPage -> TagDetailPage : displayEditForm()
activate TagDetailPage
deactivate TagDetailPage

User -> TagDetailPage : saveChanges(tagID, newData)

TagDetailPage -> TagDetailPage : validateForm(newData.name)
activate TagDetailPage
deactivate TagDetailPage

opt form invalid
    TagDetailPage -> TagDetailPage : showError("Name is required")
    activate TagDetailPage
    deactivate TagDetailPage
end

TagDetailPage -> TagController : updateTag(tagID, newData)
activate TagController

TagController -> TagRepository : update(tagID, newData)
activate TagRepository
TagRepository --> TagController : updateStatus
deactivate TagRepository

alt name already exists
    TagController --> TagDetailPage : error "Name already exists"
    TagDetailPage -> TagDetailPage : showError("Name already exists")
    activate TagDetailPage
    deactivate TagDetailPage
else update successful
    TagController --> TagDetailPage : updatedTagData
    deactivate TagController
    TagDetailPage -> TagDetailPage : reloadDetail(data)
    activate TagDetailPage
    deactivate  TagDetailPage
end
@enduml
