@startuml
mainframe "**sd** UbahTagGroup"

hide footbox

actor "**: User**" as User
boundary "**: TagGroupPage**" as TagGroupDetailPage
control "**: TagGroupController**" as TagGroupController
entity  "**: TagGroup**" as TagGroupRepository

User -> TagGroupDetailPage : clickEdit()
activate TagGroupDetailPage

TagGroupDetailPage -> TagGroupDetailPage : displayEditForm()
activate TagGroupDetailPage
deactivate TagGroupDetailPage

User -> TagGroupDetailPage : saveChanges(tagGroupID, newData)

TagGroupDetailPage -> TagGroupDetailPage : validateForm(newData.name)
activate TagGroupDetailPage
deactivate TagGroupDetailPage

opt form invalid
    TagGroupDetailPage -> TagGroupDetailPage : showError("Name is required")
    activate TagGroupDetailPage
    deactivate TagGroupDetailPage
end

TagGroupDetailPage -> TagGroupController : updateTagGroup(tagGroupID, newData)
activate TagGroupController

TagGroupController -> TagGroupRepository : update(tagGroupID, newData)
activate TagGroupRepository
TagGroupRepository --> TagGroupController : updateStatus
deactivate TagGroupRepository

alt name already exists
    TagGroupController --> TagGroupDetailPage : error "Name already exists"
    TagGroupDetailPage -> TagGroupDetailPage : showError("Name already exists")
    activate TagGroupDetailPage
    deactivate TagGroupDetailPage
else update successful
    TagGroupController --> TagGroupDetailPage : updatedTagGroupData
    deactivate TagGroupController
    TagGroupDetailPage -> TagGroupDetailPage : reloadDetail(data)
    activate TagGroupDetailPage
    deactivate TagGroupDetailPage
end
@enduml
